<li>
                              <a href="blog_1.php">ബ്ലോഗ്</a>
                              <ul>
                                 <li>
                                    <a href="blog_1.php">Blog 1</a>
                                    <ul>
                                       <li><a href="blog_1.php">Right sidebar</a></li>
                                       <li><a href="blog_1_l_sidebar.php">Left sidebar</a></li>
                                       <li><a href="blog_1_full_width.php">Full Width</a></li>
                                    </ul>
                                 </li>
                                 <li>
                                    <a href="blog_2.php">Blog 2</a>
                                    <ul>
                                       <li><a href="blog_2.php">Right sidebar</a></li>
                                       <li><a href="blog_2_l_sidebar.php">Left sidebar</a></li>
                                       <li><a href="blog_2_full_width.php">Full Width</a></li>
                                    </ul>
                                 </li>
                                 <li>
                                    <a href="single_post.php">Post Single</a>
                                    <ul>
                                       <li><a href="single_post.php">Right sidebar</a></li>
                                       <li><a href="single_post_l_sidebar.php">Left sidebar</a></li>
                                       <li><a href="single_post_full_width.php">Full Width</a></li>
                                    </ul>
                                 </li>
                              </ul>
                           </li>